### PR TITLE
Avoid creating orphan edges

### PR DESCRIPTION
**Pull request by iamsoorena**
before removing these lines, If user didn't make a new edge with `onCreateEdge`, we would have orphan edges.

Demo of bug:
orphaned-edge

### CODE REVIEW

**Comment by ajbogh** [comment]
This is an interesting use case. Thanks for showing it in an image!

I worry if the right approach is to remove those lines. I'll have to see what the implications are.

Another way to handle this is to call `this.setState()` again to force react-digraph to rerender with the existing graph, which should delete the extra edge. You would do this when the user presses the cancel button.

**Comment by iamsoorena** [comment]
Hi there, thanks for your response.
the graph works just fine without those lines.
I think the only reason they exist is for graph to update faster, because it sometimes takes a while for graph to re-render new edges.
If that's the case we can have some extra methods for adding edged `asynchronously` to avoid these kinds of conflicts.

**Comment by iamsoorena** [comment]
@ajbogh This is critical, the graph won't re-render only by calling `this.setState()`.
this orphaned edge won't go away even if I set completely new edges => `this.setState({edges: currentEdges.slice()})`!!! that's unacceptable.
So this orphaned edge does not go away.

**Comment by ajbogh** [comment]
Hi @iamsoorena. I plan to look into this as soon as I am complete with another priority. I apologize for the delay and the rest of the team is split with their priorities as well. Please allow me to look into this next week.

**Comment by iamsoorena** [comment]
Hi @ajbogh, we are using this library in a serious project. I have tested library without those lines a few times. there is no problem with removing those lines. those lines only introduce some buggy behavior and I will be happy If you find the time to look into this.

**Comment by iamsoorena** [comment]
@ajbogh Hi.

**Comment by ajbogh** [comment]
@iamsoorena I've asked another team member to look into this. Hopefully he can get to it soon. Thanks for the patience.

@vincentuber

**Comment by ahslr** [comment]
Hey @chiwoojo 
Did you have a chance to look at this?

**Comment by ajbogh** [comment]
I was able to test this today and found that it works fine for existing projects. Thanks for being so patient with this, and I apologize for the delay.

**Comment by ajbogh** [comment]
This is included in 6.2.0. Thanks!

**Pull request merged**
