### PR TITLE
Fix Build and use arrow functions for bindings

### PR DESCRIPTION
**Pull request by mac-s-g**
migrated handlers to arrow function definitions.  arrow functions automatically bind handlers to the `GraphView` object.

I also included updates necessary to get the build passing.  

tests and build are successful.

### CODE REVIEW

**Comment by mac-s-g** [comment]
fixes #29

**Comment by johnvf** [comment]
Hi mac-s-g,

Thanks for all of the help with this (and apologies for the late reply, I was on vacation). I've landed a couple of other pull requests and it seems this one needs a rebase now. Any chance you can rebase/resubmit this?

**Comment by mac-s-g** [comment]
no problem!  I expected that to happen.  I'll update and test again as soon as I get a chance.

thanks for following up!

**Comment by mac-s-g** [comment]
@johnvf merged, and tests are passing!

**Comment by johnvf** [comment]
Thanks a lot! Any chance you could also quickly bump the version to 3.0.3 in package.json?

**Comment by mac-s-g** [comment]
sure, i'll have that up in a moment

**Comment by mac-s-g** [comment]
patch bumped :+1:

**Pull request merged**
