### PR TITLE
Only import the expand icon

### LINKED ISSUE #108: Only import icons that are used
**Describe the bug**
This is part II of issue #106
`react-digraph` is importing all of `react-icons`, but it is only using one icon from font awesome.

**To Reproduce**

1. Checkout (or merge) https://github.com/uber/react-digraph/pull/107
2. `yarn && yarn analyze-bundle` 
3. look at the dependency output 

**Expected behavior**
`react-digraph` should only need to output the one icon that is being used in the final production build. Optimizing this is fairly straight forward, and will reduce the prod build of `react-digraph` by about 60%.

**Screenshots**
screen shot 2019-02-21 at 5 00 03 am

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
I plan on fixing this myself. This issue is only for tracking purposes.

### PR DESCRIPTION
**Pull request by rileyhilliard**
Only import font-awesome `expand` icon instead of the entire `react-icons` library. 
This optimization reduces the production build output by 374k, a 68% reduction in asset size.

**How to test this**:
1. checkout the branch locally
2. install dependency changes via `yarn` or `npm install`
3. run `yarn example` and verify everything looks normal
4. merge https://github.com/uber/react-digraph/pull/107 and run `yarn analyze-bundle` to see prod build stats.

Visualized improvements via `webpack-build-analyzer`:

screen shot 2019-02-24 at 8 35 41 am
screen shot 2019-02-24 at 8 29 26 am

Resolved #108

### CODE REVIEW

**Comment by rileyhilliard** [comment]
@ajbogh / @chiwoojo
This will reduce the production build asset size of `react-digraph` by 68% ☝️

**Comment by ajbogh** [comment]
There are 4 failing tests with the following error:

```
 FAIL  __tests__/components/graph-controls.test.js
  ● Test suite failed to run

    TypeError: First argument must be a string

      at HTMLReactParser (node_modules/html-react-parser/index.js:17:11)
      at Object.<anonymous> (src/components/graph-controls.js:768:177)
      at Object.<anonymous> (__tests__/components/graph-controls.test.js:9:22)
```

**Comment by rileyhilliard** [comment]
@ajbogh I was confused by the same *@fortawesome* thing, but it appears that that's [fontawesome's parent branding](https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers).

Weird, I thought I had the tests working, but it looks like that might have been before I was explicitly importing the svg asset. It looks like the issue is actually just `jest` not knowing how to import the asset. I added an icon mock that fixes the test issue 👇.
screen shot 2019-02-26 at 6 52 41 am
As a secondary precaution, I manually `grep`ed `dist/main.min.js` for the svg expand icon asset. It's forsure included properly, but jest seems to not be great at knowing how to handle certain types of assets.

**Comment by ajbogh** [comment]
Great work on this. I checked it out and it looks good. Thanks!

**Pull request merged**
