### PR TITLE
Downgrade d3 to v3.

### PR DESCRIPTION
**Pull request by vicapow**

### CODE REVIEW

**Comment by vicapow** [comment]
graph-view.js uses d3 transition. this is a d3 v3 api. https://github.com/uber/react-digraph/blob/0d950ea749cbbe596a7014cefba1684eb81cf043/src/components/graph-view.js#L623

**Comment by vicapow** [comment]
likely related to https://github.com/uber/react-digraph/issues/71

**Comment by NameFILIP** [comment]
I've checked and looks like the downgrade fixes this, but then I get `d3.zoom` is not a function

**Comment by ajbogh** [comment]
@vicapow Please provide an issue number with the PR and make sure to sign the CLA.

**Comment by vicapow** [comment]
This is broken on master. I recommend landing this and upgrading d3 later. The issue number was provided above. #71

**Comment by NameFILIP** [comment]
to clarify, I haven't been able to verify if downgrading fixes the issue. I'd investigate more why exactly the error is happening

**Comment by ajbogh** [comment]
I'm going to close this PR as the CLA hasn't been signed and the bug is fixed in #74.

**Pull request closed without merging**
